version: "3.2"
services:
  service_name:
  image: test_image
  container_name: test
  build:
   context: .
   dockerfile: "Dockerfile"
  ports:
    - "8000:8000"
  restart: unless-stopped
  env_file:
    - .env